### PR TITLE
add support for Lenovo K4 Note (A7010a48)

### PR DESCRIPTION
**Pull request by ganeshi4u**

### CODE REVIEW

**Comment by aditheking** [comment]
No

**Comment by ganeshi4u** [comment]
i have talked to @sagarshah1729

**Comment by aditheking** [comment]
Proof ?

**Comment by aditheking** [comment]
@AgentFabulous told me not to make any random guy maintainer

**Comment by ganeshi4u** [comment]
@aditheking Here's the proof and i have been added to the Official Maintainers group on Telegram. You can check with him if necessary. :)
https://ibb.co/dnqOVk
https://ibb.co/muB8wQ

**Comment by aditheking** [comment]
okay but u need to pull req in other repo's also

**Comment by ganeshi4u** [comment]
yeah thanks, i'll push the changes to other repo's once i finish making the build and thread.

**Pull request merged**
